//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18034
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crypt.Encoders.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.</summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crypt.Encoders.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Transmit binary data.
        /// </summary>
        internal static string Base64Description {
            get {
                return ResourceManager.GetString("Base64Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 32-bit checksum.
        /// </summary>
        internal static string Crc32Description {
            get {
                return ResourceManager.GetString("Crc32Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Data Encryption Standard algorithm.
        /// </summary>
        internal static string DesDescription {
            get {
                return ResourceManager.GetString("DesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Eligible characters into HTML entities.
        /// </summary>
        internal static string HtmlDescription {
            get {
                return ResourceManager.GetString("HtmlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alphabetical characters in lower case.
        /// </summary>
        internal static string LowerCaseDescription {
            get {
                return ResourceManager.GetString("LowerCaseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à RSA Data Security MD2 Message-Digest algorithm.
        /// </summary>
        internal static string MD2Description {
            get {
                return ResourceManager.GetString("MD2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à RSA Data Security MD4 Message-Digest algorithm.
        /// </summary>
        internal static string MD4Description {
            get {
                return ResourceManager.GetString("MD4Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à RSA Data Security MD5 Message-Digest algorithm.
        /// </summary>
        internal static string MD5Description {
            get {
                return ResourceManager.GetString("MD5Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Random ASCII codes.
        /// </summary>
        internal static string RandomAsciiDescription {
            get {
                return ResourceManager.GetString("RandomAsciiDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à US Secure Hash 1 algorithm.
        /// </summary>
        internal static string Sha1Description {
            get {
                return ResourceManager.GetString("Sha1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à US Secure Hash 224 algorithm.
        /// </summary>
        internal static string Sha224Description {
            get {
                return ResourceManager.GetString("Sha224Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à US Secure Hash 256 algorithm.
        /// </summary>
        internal static string Sha256Description {
            get {
                return ResourceManager.GetString("Sha256Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à US Secure Hash 384 algorithm.
        /// </summary>
        internal static string Sha384Description {
            get {
                return ResourceManager.GetString("Sha384Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à US Secure Hash 512 algorithm.
        /// </summary>
        internal static string Sha512Description {
            get {
                return ResourceManager.GetString("Sha512Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à First letter of each word in upper case.
        /// </summary>
        internal static string TitleCaseDescription {
            get {
                return ResourceManager.GetString("TitleCaseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Triple Data Encryption Standard algorithm.
        /// </summary>
        internal static string TripleDesDescription {
            get {
                return ResourceManager.GetString("TripleDesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unix passwords.
        /// </summary>
        internal static string UnixCryptDescription {
            get {
                return ResourceManager.GetString("UnixCryptDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alphabetical characters in upper case.
        /// </summary>
        internal static string UpperCaseDescription {
            get {
                return ResourceManager.GetString("UpperCaseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Special characters into XML entities.
        /// </summary>
        internal static string XmlDescription {
            get {
                return ResourceManager.GetString("XmlDescription", resourceCulture);
            }
        }
    }
}
