//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18034
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crypt.Windows.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.</summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Crypt.Windows.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show the about {0} window.
        /// </summary>
        public static string AboutCommandStatusTip {
            get {
                return ResourceManager.GetString("AboutCommandStatusTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About {0}.
        /// </summary>
        public static string AboutCommandText {
            get {
                return ResourceManager.GetString("AboutCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Setup Error|Encoding add-ins not found.
        ///Please reinstall the application..
        /// </summary>
        public static string AddInsNotFoundError {
            get {
                return ResourceManager.GetString("AddInsNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}. All rights reserved..
        /// </summary>
        public static string ApplicationCopyright {
            get {
                return ResourceManager.GetString("ApplicationCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à String Encoding Tool.
        /// </summary>
        public static string ApplicationDescription {
            get {
                return ResourceManager.GetString("ApplicationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Icon semblable à (Icône).
        /// </summary>
        public static System.Drawing.Icon ApplicationIcon {
            get {
                object obj = ResourceManager.GetObject("ApplicationIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quit the application.
        /// </summary>
        public static string CloseCommandStatusTip {
            get {
                return ResourceManager.GetString("CloseCommandStatusTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quit.
        /// </summary>
        public static string CloseCommandText {
            get {
                return ResourceManager.GetString("CloseCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy the selection and place it into the clipboard.
        /// </summary>
        public static string CopyCommandStatusTip {
            get {
                return ResourceManager.GetString("CopyCommandStatusTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Switch the application language.
        /// </summary>
        public static string CultureControlStatusTip {
            get {
                return ResourceManager.GetString("CultureControlStatusTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cut the selection and place it into the clipboard.
        /// </summary>
        public static string CutCommandStatusTip {
            get {
                return ResourceManager.GetString("CutCommandStatusTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _Edit.
        /// </summary>
        public static string EditMenuHeader {
            get {
                return ResourceManager.GetString("EditMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Encode.
        /// </summary>
        public static string EncodeButtonLabel {
            get {
                return ResourceManager.GetString("EncodeButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Encode string with the selected method.
        /// </summary>
        public static string EncodeButtonStatusTip {
            get {
                return ResourceManager.GetString("EncodeButtonStatusTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _File.
        /// </summary>
        public static string FileMenuHeader {
            get {
                return ResourceManager.GetString("FileMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _?.
        /// </summary>
        public static string HelpMenuHeader {
            get {
                return ResourceManager.GetString("HelpMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Method:.
        /// </summary>
        public static string InputComboBoxLabel {
            get {
                return ResourceManager.GetString("InputComboBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Method used to encode the string.
        /// </summary>
        public static string InputComboBoxStatusTip {
            get {
                return ResourceManager.GetString("InputComboBoxStatusTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à String to encode:.
        /// </summary>
        public static string InputTextBoxLabel {
            get {
                return ResourceManager.GetString("InputTextBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à String which characters must be encoded.
        /// </summary>
        public static string InputTextBoxStatusTip {
            get {
                return ResourceManager.GetString("InputTextBoxStatusTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Result:.
        /// </summary>
        public static string OutputTextBoxLabel {
            get {
                return ResourceManager.GetString("OutputTextBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à String encoded by the selected method.
        /// </summary>
        public static string OutputTextBoxStatusTip {
            get {
                return ResourceManager.GetString("OutputTextBoxStatusTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paste the clipboard contents.
        /// </summary>
        public static string PasteCommandStatusTip {
            get {
                return ResourceManager.GetString("PasteCommandStatusTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open the bug tracking Web page.
        /// </summary>
        public static string ReportBugCommandStatusTip {
            get {
                return ResourceManager.GetString("ReportBugCommandStatusTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Report Bug.
        /// </summary>
        public static string ReportBugCommandText {
            get {
                return ResourceManager.GetString("ReportBugCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Restart Required|Application has to be restarted
        ///to take changes into account..
        /// </summary>
        public static string RestartProgramInfo {
            get {
                return ResourceManager.GetString("RestartProgramInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show or hide the menu bar.
        /// </summary>
        public static string ShowMenuBarCommandStatusTip {
            get {
                return ResourceManager.GetString("ShowMenuBarCommandStatusTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Menu Bar.
        /// </summary>
        public static string ShowMenuBarCommandText {
            get {
                return ResourceManager.GetString("ShowMenuBarCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show or hide the status bar.
        /// </summary>
        public static string ShowStatusBarCommandStatusTip {
            get {
                return ResourceManager.GetString("ShowStatusBarCommandStatusTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Status Bar.
        /// </summary>
        public static string ShowStatusBarCommandText {
            get {
                return ResourceManager.GetString("ShowStatusBarCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show or hide the tool bar.
        /// </summary>
        public static string ShowToolBarCommandStatusTip {
            get {
                return ResourceManager.GetString("ShowToolBarCommandStatusTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tool Bar.
        /// </summary>
        public static string ShowToolBarCommandText {
            get {
                return ResourceManager.GetString("ShowToolBarCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open the technical support Web page.
        /// </summary>
        public static string TechnicalSupportCommandStatusTip {
            get {
                return ResourceManager.GetString("TechnicalSupportCommandStatusTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Technical Support.
        /// </summary>
        public static string TechnicalSupportCommandText {
            get {
                return ResourceManager.GetString("TechnicalSupportCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel the last action.
        /// </summary>
        public static string UndoCommandStatusTip {
            get {
                return ResourceManager.GetString("UndoCommandStatusTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à _View.
        /// </summary>
        public static string ViewMenuHeader {
            get {
                return ResourceManager.GetString("ViewMenuHeader", resourceCulture);
            }
        }
    }
}
